services:
  pgdatabase:
    image: postgres
    container_name: visight-postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdatabase_data:/var/lib/postgresql
    networks:
      - visight-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: visight-pgadmin
    restart: always
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - pgdatabase
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - visight-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: visight-api
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - pgdatabase
    networks:
      - visight-network

volumes:
  pgdatabase_data:
  pgadmin_data:

networks:
  visight-network:
    driver: bridge